"""added new table name portfolio_modal

Revision ID: 28320a2d8484
Revises: 
Create Date: 2021-04-11 22:46:47.550311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28320a2d8484'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_modal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('m_data_modal', sa.String(length=120), nullable=True),
    sa.Column('portfolimodalimages_name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['portfolimodalimages_name'], ['portfolio_images.p_img'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_modal')
    # ### end Alembic commands ###
