"""added new table and foreign key

Revision ID: 39dfa18a81e4
Revises: 
Create Date: 2021-04-02 09:52:37.274862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39dfa18a81e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cat_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p_img', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p_title', sa.String(length=140), nullable=True),
    sa.Column('p_icon', sa.String(length=70), nullable=True),
    sa.Column('data_modal', sa.String(length=100), nullable=True),
    sa.Column('portfoliocategory_name', sa.String(length=100), nullable=False),
    sa.Column('portfolioimages_name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['portfoliocategory_name'], ['portfolio_category.cat_name'], ),
    sa.ForeignKeyConstraint(['portfolioimages_name'], ['portfolio_images.p_img'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio')
    op.drop_table('portfolio_images')
    op.drop_table('portfolio_category')
    # ### end Alembic commands ###
