"""Added new column

Revision ID: 943a65fa372c
Revises: 
Create Date: 2021-03-26 16:46:49.728508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943a65fa372c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coding_skills', sa.Column('cs_number', sa.String(length=70), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coding_skills', 'cs_number')
    # ### end Alembic commands ###
