"""Added new table name Reviews

Revision ID: abcc249123ee
Revises: 943a65fa372c
Create Date: 2021-03-26 18:35:53.669537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abcc249123ee'
down_revision = '943a65fa372c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('r_img', sa.String(length=200), nullable=True),
    sa.Column('r_name', sa.String(length=140), nullable=True),
    sa.Column('r_company', sa.String(length=150), nullable=True),
    sa.Column('r_icon', sa.String(length=100), nullable=True),
    sa.Column('r_subject', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
