"""Added new table name Contact

Revision ID: e43888de51a5
Revises: 2888ba6b3525
Create Date: 2021-03-27 19:01:58.714270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e43888de51a5'
down_revision = '2888ba6b3525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=140), nullable=True),
    sa.Column('email', sa.String(length=140), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact')
    # ### end Alembic commands ###
